apiVersion: v1
kind: Secret
metadata:
        name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
        password: notpassword
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
        name: mysql-sc
provisioner: kubernetes.io/gce-pd
parameters:
        type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
        name: mysql-pv
        labels:
                type: local
spec:
        storageClassName: mysql-sc
        capacity:
                storage: 20Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mysql-pvc
spec:
        accessModes:
                - ReadWriteOnce
        storageClassName: mysql-sc
        resources:
                requests:
                        storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: mydb
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: mydb
        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: mydb
                spec:
                        containers:
                                - image: mysql:latest
                                  name: mydb
                                  env:
                                          - name: MYSQL_ROOT_PASSWORD
                                            valueFrom: 
                                                secretKeyRef:
                                                    name: mysql-secret
                                                    key: password
                                          - name: MYSQL_DATABASE
                                            value: campus
                                  ports:
                                          - containerPort: 3306
                                  volumeMounts:
                                          - name: mysql-persistent-storage
                                            mountPath: /var/lib/mysql
                        volumes:
                                - name: mysql-persistent-storage
                                  persistentVolumeClaim:
                                          claimName: mysql-pvc

