version: '3'

services:
        webscraper:
                build: webscraper
                #image: 127.0.0.1:30000/webscraper:0.1
                ports:
                        - 8000:5000
                          
        mydb:
                restart: always
                container_name: mydb
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: notpassword
                        MYSQL_ROOT_HOST: '%'
                        MYSQL_DATABASE: campus
                ports:
                        - "3308:3306"
                volumes:
                        - mysql:/var/lib/mysql
                        - mysql_config:/etc/mysql
volumes:
        mysql:
        mysql_config: 
