version: '3'

services:
        webscraper:
                build: ./WebScraper
                ports:
                        - 8000:5000
        mydb:
                restart: always
                container_name: mydb
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: notpassword
                        MYSQL_DATABASE: campus
                ports:
                        - "3306:3306"
                volumes:
                        - mysql:/var/lib/mysql
                        - mysql_config:/etc/mysql
volumes:
        mysql:
        mysql_config: 
