version: '3'

services:
#webui
        webui:
                build: webui
                image: 127.0.0.1:30000/webui:0.1
                container_name: webui
                volumes:
                        - ./webui/logs:/var/logs
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
#chatbot
        rasa:
                container_name: chatbot_rasa
                user: root
                build: chatbot
                image: 127.0.0.1:30000/chatbot_rasa:0.1
                volumes:
                        - ./chatbot/:/app
                ports:
                        - "5005:5005"
        actions:
                container_name: chatbot_actions
                build:
                        context: chatbot/actions
                image: 127.0.0.1:30000/chatbot_actions:0.1
                volumes:
                        - ./chatbot/actions:/app/actions
                        - ./chatbot/data:/app/data
                ports:
                        - "5055:5055"
#webscraper
        webscraper:
                build: webscraper
                image: 127.0.0.1:30000/webscraper:0.1
                ports:
                        - "8000:5000"
#database               
        mydb:
                restart: always
                container_name: mydb
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: notpassword
                        MYSQL_ROOT_HOST: '%'
                        MYSQL_DATABASE: campus
                ports:
                        - "3308:3306"
                volumes:
                        - mysql:/var/lib/mysql
                        - mysql_config:/etc/mysql
volumes:
        mysql:
        mysql_config: 
