version: '3'

services:
        mysql-development:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: notpassword
                        MYSQL_DATABASE: events
                ports:
                        - "3308:3306"
