apiVersion: apps/v1
kind: Deployment
metadata:
        name: mydb
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: mydb
        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: mydb
                spec:
                        containers:
                                - image: mysql:latest
                                  name: mydb
                                  env:
                                          - name: MYSQL_ROOT_PASSWORD
                                            valueFrom: 
                                                secretKeyRef:
                                                    name: mysql-secret
                                                    key: password
                                          - name: MYSQL_DATABASE
                                            value: events
                                  ports:
                                          - containerPort: 3306
                                  volumeMounts:
                                          - name: mysql-persistent-storage
                                            mountPath: /var/lib/mysql
                        volumes:
                                - name: mysql-persistent-storage
                                  persistentVolumeClaim:
                                          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
        name: mydb
spec:
        ports:
                - port: 3306
                  protocol: TCP
        selector:
                app: mydb
