apiVersion: v1
kind: Service
metadata:
        name: chatbot
spec:
        ports:
                - name: rasa
                  protocol: TCP
                  port: 5005
                - name: actions
                  protocol: TCP
                  port: 5055
