apiVersion: apps/v1
kind: Deployment
metadata:
        name: chatbot
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: chatbot
        template:
                metadata:
                        labels:
                                app: chatbot
                spec:
                        containers:
                                - name: chatbot-rasa
                                  image: 127.0.0.1:chatbot-rasa:0.1
                                  ports:
                                          - containerPort: 5005
                                - name: chatbot-actions
                                  image: 127.0.0.1:chatbot-actions:0.1
                                  ports:
                                          - containerPort: 5055
